"""add_horometer_unit_description_location_to_machines_and_spare_parts_extended_fields

Revision ID: 378e3387584e
Revises: 475c3f09885a
Create Date: 2026-07-19 13:20:36.872356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378e3387584e'
down_revision: Union[str, Sequence[str], None] = '475c3f09885a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='Horas' poblará los registros existentes antes de eliminar el default
    op.add_column('machines', sa.Column('horometer_unit', sa.String(length=20), nullable=False, server_default='Horas'))
    op.add_column('machines', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('machines', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('maintenance_orders', 'labor_cost')
    op.drop_column('maintenance_orders', 'hours_worked')
    op.add_column('spare_parts', sa.Column('part_number', sa.String(length=100), nullable=True))
    op.add_column('spare_parts', sa.Column('unit_of_measure', sa.String(length=50), nullable=True))
    op.add_column('spare_parts', sa.Column('internal_code', sa.String(length=100), nullable=True))
    op.add_column('spare_parts', sa.Column('unit_cost_usd', sa.Float(), nullable=True))
    op.create_index(op.f('ix_spare_parts_internal_code'), 'spare_parts', ['internal_code'], unique=True)
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_internal_code'), table_name='spare_parts')
    op.drop_column('spare_parts', 'unit_cost_usd')
    op.drop_column('spare_parts', 'internal_code')
    op.drop_column('spare_parts', 'unit_of_measure')
    op.drop_column('spare_parts', 'part_number')
    op.add_column('maintenance_orders', sa.Column('hours_worked', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('maintenance_orders', sa.Column('labor_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('machines', 'location')
    op.drop_column('machines', 'description')
    op.drop_column('machines', 'horometer_unit')
    # ### end Alembic commands ###
