version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: web
    networks:
      - dokploy-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ > /dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  dokploy-network:
    name: dokploy-network
