/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRepuestosRouteImport } from './routes/_authenticated.repuestos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated.reportes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated.auditoria'
import { Route as AuthenticatedMaquinariaIndexRouteImport } from './routes/_authenticated.maquinaria.index'
import { Route as AuthenticatedMantenimientoIndexRouteImport } from './routes/_authenticated.mantenimiento.index'
import { Route as AuthenticatedMaquinariaNuevaRouteImport } from './routes/_authenticated.maquinaria.nueva'
import { Route as AuthenticatedMantenimientoIdRouteImport } from './routes/_authenticated.mantenimiento.$id'
import { Route as AuthenticatedMaquinariaIdIndexRouteImport } from './routes/_authenticated.maquinaria.$id.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepuestosRoute = AuthenticatedRepuestosRouteImport.update({
  id: '/repuestos',
  path: '/repuestos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaquinariaIndexRoute =
  AuthenticatedMaquinariaIndexRouteImport.update({
    id: '/maquinaria/',
    path: '/maquinaria/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMantenimientoIndexRoute =
  AuthenticatedMantenimientoIndexRouteImport.update({
    id: '/mantenimiento/',
    path: '/mantenimiento/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaquinariaNuevaRoute =
  AuthenticatedMaquinariaNuevaRouteImport.update({
    id: '/maquinaria/nueva',
    path: '/maquinaria/nueva',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMantenimientoIdRoute =
  AuthenticatedMantenimientoIdRouteImport.update({
    id: '/mantenimiento/$id',
    path: '/mantenimiento/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaquinariaIdIndexRoute =
  AuthenticatedMaquinariaIdIndexRouteImport.update({
    id: '/maquinaria/$id/',
    path: '/maquinaria/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/repuestos': typeof AuthenticatedRepuestosRoute
  '/mantenimiento/$id': typeof AuthenticatedMantenimientoIdRoute
  '/maquinaria/nueva': typeof AuthenticatedMaquinariaNuevaRoute
  '/mantenimiento/': typeof AuthenticatedMantenimientoIndexRoute
  '/maquinaria/': typeof AuthenticatedMaquinariaIndexRoute
  '/maquinaria/$id/': typeof AuthenticatedMaquinariaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/repuestos': typeof AuthenticatedRepuestosRoute
  '/mantenimiento/$id': typeof AuthenticatedMantenimientoIdRoute
  '/maquinaria/nueva': typeof AuthenticatedMaquinariaNuevaRoute
  '/mantenimiento': typeof AuthenticatedMantenimientoIndexRoute
  '/maquinaria': typeof AuthenticatedMaquinariaIndexRoute
  '/maquinaria/$id': typeof AuthenticatedMaquinariaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/repuestos': typeof AuthenticatedRepuestosRoute
  '/_authenticated/mantenimiento/$id': typeof AuthenticatedMantenimientoIdRoute
  '/_authenticated/maquinaria/nueva': typeof AuthenticatedMaquinariaNuevaRoute
  '/_authenticated/mantenimiento/': typeof AuthenticatedMantenimientoIndexRoute
  '/_authenticated/maquinaria/': typeof AuthenticatedMaquinariaIndexRoute
  '/_authenticated/maquinaria/$id/': typeof AuthenticatedMaquinariaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auditoria'
    | '/dashboard'
    | '/reportes'
    | '/repuestos'
    | '/mantenimiento/$id'
    | '/maquinaria/nueva'
    | '/mantenimiento/'
    | '/maquinaria/'
    | '/maquinaria/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auditoria'
    | '/dashboard'
    | '/reportes'
    | '/repuestos'
    | '/mantenimiento/$id'
    | '/maquinaria/nueva'
    | '/mantenimiento'
    | '/maquinaria'
    | '/maquinaria/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/auditoria'
    | '/_authenticated/dashboard'
    | '/_authenticated/reportes'
    | '/_authenticated/repuestos'
    | '/_authenticated/mantenimiento/$id'
    | '/_authenticated/maquinaria/nueva'
    | '/_authenticated/mantenimiento/'
    | '/_authenticated/maquinaria/'
    | '/_authenticated/maquinaria/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repuestos': {
      id: '/_authenticated/repuestos'
      path: '/repuestos'
      fullPath: '/repuestos'
      preLoaderRoute: typeof AuthenticatedRepuestosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maquinaria/': {
      id: '/_authenticated/maquinaria/'
      path: '/maquinaria'
      fullPath: '/maquinaria/'
      preLoaderRoute: typeof AuthenticatedMaquinariaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mantenimiento/': {
      id: '/_authenticated/mantenimiento/'
      path: '/mantenimiento'
      fullPath: '/mantenimiento/'
      preLoaderRoute: typeof AuthenticatedMantenimientoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maquinaria/nueva': {
      id: '/_authenticated/maquinaria/nueva'
      path: '/maquinaria/nueva'
      fullPath: '/maquinaria/nueva'
      preLoaderRoute: typeof AuthenticatedMaquinariaNuevaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mantenimiento/$id': {
      id: '/_authenticated/mantenimiento/$id'
      path: '/mantenimiento/$id'
      fullPath: '/mantenimiento/$id'
      preLoaderRoute: typeof AuthenticatedMantenimientoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maquinaria/$id/': {
      id: '/_authenticated/maquinaria/$id/'
      path: '/maquinaria/$id'
      fullPath: '/maquinaria/$id/'
      preLoaderRoute: typeof AuthenticatedMaquinariaIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedRepuestosRoute: typeof AuthenticatedRepuestosRoute
  AuthenticatedMantenimientoIdRoute: typeof AuthenticatedMantenimientoIdRoute
  AuthenticatedMaquinariaNuevaRoute: typeof AuthenticatedMaquinariaNuevaRoute
  AuthenticatedMantenimientoIndexRoute: typeof AuthenticatedMantenimientoIndexRoute
  AuthenticatedMaquinariaIndexRoute: typeof AuthenticatedMaquinariaIndexRoute
  AuthenticatedMaquinariaIdIndexRoute: typeof AuthenticatedMaquinariaIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedRepuestosRoute: AuthenticatedRepuestosRoute,
  AuthenticatedMantenimientoIdRoute: AuthenticatedMantenimientoIdRoute,
  AuthenticatedMaquinariaNuevaRoute: AuthenticatedMaquinariaNuevaRoute,
  AuthenticatedMantenimientoIndexRoute: AuthenticatedMantenimientoIndexRoute,
  AuthenticatedMaquinariaIndexRoute: AuthenticatedMaquinariaIndexRoute,
  AuthenticatedMaquinariaIdIndexRoute: AuthenticatedMaquinariaIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
